channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pip
  - pandas
  - scikit-learn
  - matplotlib
  - xarray
  - bottleneck
  - requests
  - rasterio
  - pyproj
  - beautifulsoup4
  - rioxarray
  - geopandas
  - shapely

  - pip:
    - mimesis